language: node_js

node_js:
  - "iojs-v1.4.3"

addons:
  code_climate:
    repo_token: 813ed63f61309afa14092c9928f9ffee8b7b4187b1c53b4d89048af8a1e06aa1

script:
  - npm run test:cov

env:
  - DB_DIALECT=mysql DB_NAME=doclab_test DB_USER=root DB_PASS=""
  - DB_DIALECT=postgres DB_NAME=doclab_test DB_USER=postgres DB_PASS=""

before_script:
  - mysql -e 'create database doclab_test;'
  - psql -c 'create database doclab_test;' -U postgres

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate

cache:
  directories:
    - node_modules

services:
  - redis-server
