language: node_js

node_js:
  - "iojs-v1.4.3"

addons:
  code_climate:
    repo_token: dc2d6c4eea32e05ae490a266bd5d456a98ebfd1a43bf6b8326b1838c86e52b89

script:
  - npm run test:cov

env:
  - DB_DIALECT=mysql DB_NAME=doclab_test DB_USER=root DB_PASS=""
  - DB_DIALECT=postgres DB_NAME=doclab_test DB_USER=postgres DB_PASS=""

before_script:
  - mysql -e 'create database doclab_test;'
  - psql -c 'create database doclab_test;' -U postgres

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate

cache:
  directories:
    - node_modules

services:
  - redis-server
